image: ubuntu:latest

variables:
  PROJECT_DIR: "src/"

stages:
  - lint
  - tests

default:
  tags:
    - docker
  before_script:
    - apt-get update && apt-get -y install make gcc clang-format
    - cd ${PROJECT_DIR}

lint:
  stage: lint
  script:
    - make lint

tests:
  stage: tests
  script:
    - make test
